server:
  port: 8700

spring:
  application:
    name: receiver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8600/eureka/